spring:
  application:
    name: blog-admin

  profiles:
    active: dev

  # Redis配置
  # Redis服务器地址
  redis:
    host: 47.108.209.62
    port: 6379  # 端口
    password: '000928'
    database: 0  # 数据库索引
    lettuce:
      pool:
        max-active: 50  # 最大连接数
        max-wait: 3000  # 最大阻塞等待时间
        max-idle: 20  # 最大空闲连接
        min-idle: 2  # 最小空间连接
    timeout: 60000 # 连接超时时间（毫秒）

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
