server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://47.108.209.62:3306/myweb?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: '000928'
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource