spring:
  application:
    name: blog-admin

  profiles:
    active: dev

  # Redis配置
  redis:
    host: 47.108.209.62
    port: 6379  # 端口
    password: '000928'
    database: 0  # 数据库索引
    lettuce:
      pool:
        max-active: 50  # 最大连接数
        max-wait: 3000  # 最大阻塞等待时间
        max-idle: 20  # 最大空闲连接
        min-idle: 2  # 最小空间连接
    timeout: 60000 # 连接超时时间（毫秒）

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  # 发送邮件配置
  mail:
    host: smtp.qq.com # 设置邮箱主机
    username: 1552589784@qq.com # 设置用户名
    password: pfhogftiaugdbafg # 设置密码，开启SMTP的授权码

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# 七牛云配置
oos:
  qiniu:
    domain: img.mrqinzh.info
    bucketname: mrqinzh-blog
    access-key: sKhKRCxpKHgYW-gy5g4Vzoos76jT1AA9Um7heSwC
    secret-key: KBvSkna0rxl2ucTXltdA6wfzqZxAZs-jpESoNaEp

#server:
#  ssl:
#    key-store: classpath:6138774_www.mrqinzh.info.pfx #拷贝到根目录的证书文件
#    key-store-password: tK75MMVp #密码(下载tomcat证书压缩包里的txt文件)
#    key-store-type: U0Iu879t       #固定写法
