server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://47.108.209.62:3306/myweb?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: '000928'
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 七牛云配置
mrqinzh:
  blog:
    oss:
      client: QINIUYUN
      domain: img.mrqinzh.com
      bucketname: mrqinzh-blog
      access-key: sKhKRCxpKHgYW-gy5g4Vzoos76jT1AA9Um7heSwC
      secret-key: KBvSkna0rxl2ucTXltdA6wfzqZxAZs-jpESoNaEp